# Generated by Claude Sonnet 4 
# 8-1-2025

import requests
import pandas as pd
from typing import Dict, List, Optional

class WHOGHOClient:
    """Client for accessing WHO Global Health Observatory (GHO) API data."""
    
    def __init__(self):
        self.base_url = "https://ghoapi.azureedge.net/api"
        self.session = requests.Session()
        
    def get_indicator_data(self, indicator_code: str, params: Optional[Dict] = None) -> Dict:
        """
        Retrieve data for a specific indicator from the WHO GHO API.
        
        Args:
            indicator_code: The WHO indicator code (e.g., 'WHOSIS_000002' for HALE)
            params: Additional query parameters for filtering
            
        Returns:
            Dictionary containing the API response
        """
        url = f"{self.base_url}/{indicator_code}"
        
        try:
            response = self.session.get(url, params=params, timeout=30)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            print(f"Error fetching data for {indicator_code}: {e}")
            return {}
    
    def get_hale_data(self, years: Optional[List[int]] = None) -> pd.DataFrame:
        """
        Retrieve Healthy Life Expectancy (HALE) data for all countries by sex.
        
        Args:
            years: List of specific years to retrieve. If None, gets all available years.
            
        Returns:
            Pandas DataFrame with HALE data
        """
        print("Fetching HALE data from WHO GHO API...")
        
        # WHOSIS_000002 is the indicator code for HALE at birth
        data = self.get_indicator_data("WHOSIS_000002")
        
        if not data or 'value' not in data:
            print("No data retrieved from API")
            return pd.DataFrame()
        
        records = []
        
        for item in data['value']:
            try:
                record = {
                    'Country': item.get('SpatialDim', ''),
                    'CountryCode': item.get('SpatialDimType', ''),
                    'Year': item.get('TimeDim', ''),
                    'Sex': self._parse_sex_dimension(item.get('Dim1', '')),
                    'HALE_Years': item.get('NumericValue', None),
                    'HALE_Low': item.get('Low', None),
                    'HALE_High': item.get('High', None),
                    'Comments': item.get('Comments', ''),
                    'DataSource': item.get('DataSourceDim', ''),
                }
                
                # Filter by years if specified
                if years is None or int(record['Year']) in years:
                    records.append(record)
                    
            except (ValueError, TypeError) as e:
                print(f"Error processing record: {e}")
                continue
        
        df = pd.DataFrame(records)
        
        # Clean and format the data
        if not df.empty:
            df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
            df['HALE_Years'] = pd.to_numeric(df['HALE_Years'], errors='coerce')
            df['HALE_Low'] = pd.to_numeric(df['HALE_Low'], errors='coerce')
            df['HALE_High'] = pd.to_numeric(df['HALE_High'], errors='coerce')
            
            # Sort by country, sex, and year
            df = df.sort_values(['Country', 'Sex', 'Year']).reset_index(drop=True)
        
        print(f"Retrieved {len(df)} records")
        return df
    
    def _parse_sex_dimension(self, dim_value: str) -> str:
        """Parse the sex dimension value into readable format."""
        sex_mapping = {
            'MLE': 'Male',
            'FMLE': 'Female',
            'BTSX': 'Both sexes',
            '': 'Unknown'
        }
        return sex_mapping.get(dim_value, dim_value)
    
    def get_countries_list(self) -> pd.DataFrame:
        """Get list of available countries."""
        try:
            url = f"{self.base_url}/DIMENSION/COUNTRY/DimensionValues"
            response = self.session.get(url, timeout=30)
            response.raise_for_status()
            data = response.json()
            
            countries = []
            for item in data.get('value', []):
                countries.append({
                    'CountryCode': item.get('Code', ''),
                    'CountryName': item.get('Title', ''),
                    'ParentCode': item.get('ParentCode', ''),
                    'ParentTitle': item.get('ParentTitle', '')
                })
            
            return pd.DataFrame(countries)
        except requests.exceptions.RequestException as e:
            print(f"Error fetching countries list: {e}")
            return pd.DataFrame()

    def get_cardiovascular_death_rates(self, years: Optional[List[int]] = None) -> pd.DataFrame:
        """
        Retrieve age-standardized cardiovascular disease death rates by gender.
        
        Args:
            years: List of specific years to retrieve. If None, gets all available years.
            
        Returns:
            Pandas DataFrame with cardiovascular death rate data by gender
        """
        print("Fetching cardiovascular disease death rates from WHO GHO API...")
        
        # Search for cardiovascular disease indicators first
        print("Searching for cardiovascular disease indicators...")
        cardio_indicators = self.search_indicators("cardiovascular")
        if not cardio_indicators.empty:
            print("Found cardiovascular indicators:")
            print(cardio_indicators[['IndicatorCode', 'IndicatorName']].to_string(index=False))
            print()
        
        # Also search for "death rate" to find mortality indicators
        death_indicators = self.search_indicators("death rate")
        if not death_indicators.empty:
            print("Found death rate indicators:")
            print(death_indicators[['IndicatorCode', 'IndicatorName']].to_string(index=False))
            print()
        
        # Try the specific indicator code for cardiovascular disease death rates
        # MDG_0000000007 is often used for age-standardized death rates
        # Let's try multiple potential codes
        potential_codes = [
            "WHS2_161",  # Age-standardized mortality rate by cause - Cardiovascular
            "SA_0000001444",  # Age-standardized death rates, ischaemic heart disease
            "MDG_0000000007",  # Age-standardized death rate
            "NCD_MORT_30_70",  # NCD mortality
            "MDG_0000000008",  # Another mortality indicator
        ]
        
        all_data = []
        
        for code in potential_codes:
            print(f"Trying indicator code: {code}")
            data = self.get_indicator_data(code)
            
            if data and 'value' in data:
                print(f"Found data for {code}")
                
                for item in data['value']:
                    try:
                        # For cardiovascular-specific indicators, include all data
                        # For general indicators, check if this is cardiovascular disease related
                        indicator_name = item.get('IndicatorName', '').lower()
                        if (code in ["WHS2_161", "SA_0000001444"] or 
                            any(term in indicator_name for term in ['cardiovascular', 'heart', 'circulatory', 'ischaemic'])):
                            record = {
                                'IndicatorCode': code,
                                'IndicatorName': item.get('IndicatorName', ''),
                                'Country': item.get('SpatialDim', ''),
                                'CountryCode': item.get('SpatialDimType', ''),
                                'Year': item.get('TimeDim', ''),
                                'Sex': self._parse_sex_dimension(item.get('Dim1', '')),
                                'DeathRate': item.get('NumericValue', None),
                                'DeathRate_Low': item.get('Low', None),
                                'DeathRate_High': item.get('High', None),
                                'Comments': item.get('Comments', ''),
                                'DataSource': item.get('DataSourceDim', ''),
                            }
                            
                            # Filter by years if specified
                            if years is None or int(record['Year']) in years:
                                all_data.append(record)
                                
                    except (ValueError, TypeError) as e:
                        print(f"Error processing record: {e}")
                        continue
        
        df = pd.DataFrame(all_data)
        
        # Clean and format the data
        if not df.empty:
            df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
            df['DeathRate'] = pd.to_numeric(df['DeathRate'], errors='coerce')
            df['DeathRate_Low'] = pd.to_numeric(df['DeathRate_Low'], errors='coerce')
            df['DeathRate_High'] = pd.to_numeric(df['DeathRate_High'], errors='coerce')
            
            # Sort by country, sex, and year
            df = df.sort_values(['Country', 'Sex', 'Year']).reset_index(drop=True)
        
        print(f"Retrieved {len(df)} cardiovascular death rate records")
        return df

    def search_indicators(self, search_term: str) -> pd.DataFrame:
        """
        Search for indicators containing a specific term.
        
        Args:
            search_term: Term to search for in indicator names
            
        Returns:
            DataFrame with matching indicators
        """
        try:
            url = f"{self.base_url}/Indicator"
            params = {"$filter": f"contains(IndicatorName,'{search_term}')"}
            response = self.session.get(url, params=params, timeout=30)
            response.raise_for_status()
            data = response.json()
            
            indicators = []
            for item in data.get('value', []):
                indicators.append({
                    'IndicatorCode': item.get('IndicatorCode', ''),
                    'IndicatorName': item.get('IndicatorName', ''),
                    'Language': item.get('Language', ''),
                    'PublishState': item.get('PublishState', '')
                })
            
            return pd.DataFrame(indicators)
        except requests.exceptions.RequestException as e:
            print(f"Error searching indicators: {e}")
            return pd.DataFrame()

def main():
    """Main function to demonstrate usage of the WHO GHO API client."""
    
    # Initialize the client
    client = WHOGHOClient()
    
    # First, let's verify the HALE indicator code by searching
    print("=== Searching for HALE indicators ===")
    hale_indicators = client.search_indicators("healthy life expectancy")
    if not hale_indicators.empty:
        print("Found HALE indicators:")
        print(hale_indicators[['IndicatorCode', 'IndicatorName']].to_string(index=False))
        print()
    
    # Also search for just "HALE"
    hale_indicators2 = client.search_indicators("HALE")
    if not hale_indicators2.empty:
        print("Found indicators containing 'HALE':")
        print(hale_indicators2[['IndicatorCode', 'IndicatorName']].to_string(index=False))
        print()
    
    # Example 1: Get all HALE data
    print("=== Example 1: Getting all HALE data ===")
    hale_df = client.get_hale_data()
    
    if not hale_df.empty:
        print(f"Total records: {len(hale_df)}")
        print(f"Countries: {hale_df['Country'].nunique()}")
        print(f"Years covered: {hale_df['Year'].min():.0f} - {hale_df['Year'].max():.0f}")
        print(f"Sex categories: {hale_df['Sex'].unique()}")
        print("\nSample data:")
        print(hale_df.head(10))
    
    # Example 2: Get data for specific years
    print("\n=== Example 2: Getting HALE data for recent years (2015-2023) ===")
    recent_years = list(range(2015, 2024))
    recent_hale_df = client.get_hale_data(years=recent_years)
    
    if not recent_hale_df.empty:
        print(f"Records for {recent_years}: {len(recent_hale_df)}")
        print("\nSample recent data:")
        print(recent_hale_df.head())
    
    # Example 3: Analyze data by sex
    if not hale_df.empty:
        print("\n=== Example 3: HALE statistics by sex ===")
        sex_stats = hale_df.groupby('Sex')['HALE_Years'].agg(['count', 'mean', 'std']).round(2)
        print(sex_stats)
    
    # Example 4: Get countries with highest/lowest HALE (most recent data)
    if not hale_df.empty:
        print("\n=== Example 4: Countries with highest/lowest HALE (most recent year) ===")
        latest_year = hale_df['Year'].max()
        latest_data = hale_df[(hale_df['Year'] == latest_year) & (hale_df['Sex'] == 'Both sexes')]
        
        if not latest_data.empty:
            print(f"\nTop 10 countries with highest HALE in {latest_year:.0f}:")
            top_10 = latest_data.nlargest(10, 'HALE_Years')[['Country', 'HALE_Years']]
            print(top_10.to_string(index=False))
            
            print(f"\nBottom 10 countries with lowest HALE in {latest_year:.0f}:")
            bottom_10 = latest_data.nsmallest(10, 'HALE_Years')[['Country', 'HALE_Years']]
            print(bottom_10.to_string(index=False))
    
    # Example 5: Save data to CSV
    if not hale_df.empty:
        filename = 'who_hale_data.csv'
        hale_df.to_csv(filename, index=False)
        print(f"\n=== Data saved to {filename} ===")
    
    # Example 6: Get list of countries
    print("\n=== Example 6: Getting countries list ===")
    countries_df = client.get_countries_list()
    if not countries_df.empty:
        print(f"Total countries/regions: {len(countries_df)}")
        print("Sample countries:")
        print(countries_df.head())
    
    # NEW: Cardiovascular Disease Death Rates
    print("\n" + "="*60)
    print("=== CARDIOVASCULAR DISEASE DEATH RATES BY GENDER ===")
    print("="*60)
    
    # Get cardiovascular death rates
    cardio_df = client.get_cardiovascular_death_rates()
    
    if not cardio_df.empty:
        print(f"\nTotal cardiovascular death rate records: {len(cardio_df)}")
        print(f"Countries: {cardio_df['Country'].nunique()}")
        print(f"Years covered: {cardio_df['Year'].min():.0f} - {cardio_df['Year'].max():.0f}")
        print(f"Sex categories: {cardio_df['Sex'].unique()}")
        print(f"Indicators found: {cardio_df['IndicatorName'].unique()}")
        
        print("\nSample cardiovascular death rate data:")
        print(cardio_df.head(10))
        
        # Analyze by gender
        print("\n=== Cardiovascular Death Rate Statistics by Gender ===")
        gender_stats = cardio_df.groupby('Sex')['DeathRate'].agg(['count', 'mean', 'std']).round(2)
        print(gender_stats)
        
        # Get recent data (last 5 years)
        recent_years = list(range(2019, 2024))
        recent_cardio_df = client.get_cardiovascular_death_rates(years=recent_years)
        
        if not recent_cardio_df.empty:
            print(f"\n=== Recent Cardiovascular Death Rates (2019-2023) ===")
            print(f"Records for recent years: {len(recent_cardio_df)}")
            
            # Compare male vs female death rates
            latest_year = recent_cardio_df['Year'].max()
            latest_cardio = recent_cardio_df[recent_cardio_df['Year'] == latest_year]
            
            if not latest_cardio.empty:
                print(f"\n=== Gender Comparison for {latest_year:.0f} ===")
                gender_comparison = latest_cardio.groupby('Sex')['DeathRate'].agg(['mean', 'std']).round(2)
                print(gender_comparison)
                
                # Countries with highest/lowest death rates by gender
                for sex in ['Male', 'Female']:
                    sex_data = latest_cardio[latest_cardio['Sex'] == sex]
                    if not sex_data.empty:
                        print(f"\nTop 10 countries with highest cardiovascular death rates ({sex}) in {latest_year:.0f}:")
                        top_10 = sex_data.nlargest(10, 'DeathRate')[['Country', 'DeathRate']]
                        print(top_10.to_string(index=False))
                        
                        print(f"\nBottom 10 countries with lowest cardiovascular death rates ({sex}) in {latest_year:.0f}:")
                        bottom_10 = sex_data.nsmallest(10, 'DeathRate')[['Country', 'DeathRate']]
                        print(bottom_10.to_string(index=False))
        
        # Save cardiovascular data to CSV
        filename = 'who_cardiovascular_death_rates.csv'
        cardio_df.to_csv(filename, index=False)
        print(f"\n=== Cardiovascular death rate data saved to {filename} ===")
        
        # Save recent data separately
        if not recent_cardio_df.empty:
            filename_recent = 'who_cardiovascular_death_rates_recent.csv'
            recent_cardio_df.to_csv(filename_recent, index=False)
            print(f"=== Recent cardiovascular death rate data saved to {filename_recent} ===")
    
    else:
        print("No cardiovascular death rate data found. Trying alternative search terms...")
        
        # Try alternative search terms
        print("\nSearching for alternative cardiovascular indicators...")
        alt_indicators = client.search_indicators("heart disease")
        if not alt_indicators.empty:
            print("Found heart disease indicators:")
            print(alt_indicators[['IndicatorCode', 'IndicatorName']].to_string(index=False))
        
        alt_indicators2 = client.search_indicators("mortality")
        if not alt_indicators2.empty:
            print("\nFound mortality indicators:")
            print(alt_indicators2[['IndicatorCode', 'IndicatorName']].to_string(index=False))

if __name__ == "__main__":
    main()