# Generated by Claude Sonnet 4 
# 8-1-2025

import argparse
import os
import requests
import pandas as pd
from typing import Dict, List, Optional

class WHOGHOClient:
    """Client for accessing WHO Global Health Observatory (GHO) API data."""
    
    def __init__(self):
        self.base_url = "https://ghoapi.azureedge.net/api"
        self.session = requests.Session()
        
    def get_indicator_data(self, indicator_code: str, params: Optional[Dict] = None, years: Optional[List[int]] = None) -> Dict:
        """
        Retrieve data for a specific indicator from the WHO GHO API.
        
        Args:
            indicator_code: The WHO indicator code (e.g., 'WHOSIS_000002' for HALE)
            params: Additional query parameters for filtering
            years: List of years to filter. If provided, adds OData $filter for TimeDim.
            
        Returns:
            Dictionary containing the API response
        """
        url = f"{self.base_url}/{indicator_code}"
        
        # Build OData filter for years if specified
        if years is not None and len(years) > 0:
            if params is None:
                params = {}
            
            # Build OData filter string for TimeDim
            if len(years) == 1:
                # Single year: TimeDim eq 2020
                filter_str = f"TimeDim eq {years[0]}"
            elif len(years) <= 10:
                # Small list: use 'or' conditions
                filter_parts = [f"TimeDim eq {year}" for year in years]
                filter_str = " or ".join(filter_parts)
                filter_str = f"({filter_str})"
            else:
                # Large list or range: use ge/le for range
                min_year = min(years)
                max_year = max(years)
                filter_str = f"TimeDim ge {min_year} and TimeDim le {max_year}"
            
            params['$filter'] = filter_str
        
        try:
            response = self.session.get(url, params=params, timeout=30)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            print(f"Error fetching data for {indicator_code}: {e}")
            return {}
    
    def get_hale_data(self, years: Optional[List[int]] = None) -> pd.DataFrame:
        """
        Retrieve Healthy Life Expectancy (HALE) data for all countries by sex.
        
        Args:
            years: List of specific years to retrieve. If None, gets all available years.
            
        Returns:
            Pandas DataFrame with HALE data
        """
        print("Fetching HALE data from WHO GHO API...")
        
        # WHOSIS_000002 is the indicator code for HALE at birth
        # Use OData filter to get only specified years at API level
        data = self.get_indicator_data("WHOSIS_000002", years=years)
        
        if not data or 'value' not in data:
            print("No data retrieved from API")
            return pd.DataFrame()
        
        records = []
        
        for item in data['value']:
            try:
                record = {
                    'Country': item.get('SpatialDim', ''),
                    'CountryCode': item.get('SpatialDimType', ''),
                    'Year': item.get('TimeDim', ''),
                    'Sex': self._parse_sex_dimension(item.get('Dim1', '')),
                    'HALE_Years': item.get('NumericValue', None),
                    'HALE_Low': item.get('Low', None),
                    'HALE_High': item.get('High', None),
                    'Comments': item.get('Comments', ''),
                    'DataSource': item.get('DataSourceDim', ''),
                }
                
                # If years were specified, API already filtered, but double-check
                if years is None or int(record['Year']) in years:
                    records.append(record)
                    
            except (ValueError, TypeError) as e:
                print(f"Error processing record: {e}")
                continue
        
        df = pd.DataFrame(records)
        
        # Clean and format the data
        if not df.empty:
            df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
            df['HALE_Years'] = pd.to_numeric(df['HALE_Years'], errors='coerce')
            df['HALE_Low'] = pd.to_numeric(df['HALE_Low'], errors='coerce')
            df['HALE_High'] = pd.to_numeric(df['HALE_High'], errors='coerce')
            
            # Sort by country, sex, and year
            df = df.sort_values(['Country', 'Sex', 'Year']).reset_index(drop=True)
        
        print(f"Retrieved {len(df)} records")
        return df
    
    def _parse_sex_dimension(self, dim_value: str) -> str:
        """Parse the sex dimension value into readable format."""
        # Handle both formats: SEX_MLE and MLE
        dim_value_clean = dim_value.replace('SEX_', '') if dim_value else ''
        sex_mapping = {
            'MLE': 'Male',
            'FMLE': 'Female',
            'BTSX': 'Both sexes',
            '': 'Unknown'
        }
        return sex_mapping.get(dim_value_clean, dim_value)
    
    def get_countries_list(self) -> pd.DataFrame:
        """Get list of available countries."""
        try:
            url = f"{self.base_url}/DIMENSION/COUNTRY/DimensionValues"
            response = self.session.get(url, timeout=30)
            response.raise_for_status()
            data = response.json()
            
            countries = []
            for item in data.get('value', []):
                countries.append({
                    'CountryCode': item.get('Code', ''),
                    'CountryName': item.get('Title', ''),
                    'ParentCode': item.get('ParentCode', ''),
                    'ParentTitle': item.get('ParentTitle', '')
                })
            
            return pd.DataFrame(countries)
        except requests.exceptions.RequestException as e:
            print(f"Error fetching countries list: {e}")
            return pd.DataFrame()

    def get_cardiovascular_death_rates(self, years: Optional[List[int]] = None) -> pd.DataFrame:
        """
        Retrieve age-standardized cardiovascular disease death rates by gender.
        
        Args:
            years: List of specific years to retrieve. If None, gets all available years.
            
        Returns:
            Pandas DataFrame with cardiovascular death rate data by gender
        """
        print("Fetching cardiovascular disease death rates from WHO GHO API...")
        
        # Search for cardiovascular disease indicators first
        print("Searching for cardiovascular disease indicators...")
        cardio_indicators = self.search_indicators("cardiovascular")
        if not cardio_indicators.empty:
            print("Found cardiovascular indicators:")
            print(cardio_indicators[['IndicatorCode', 'IndicatorName']].to_string(index=False))
            print()
        
        # Also search for "death rate" to find mortality indicators
        death_indicators = self.search_indicators("death rate")
        if not death_indicators.empty:
            print("Found death rate indicators:")
            print(death_indicators[['IndicatorCode', 'IndicatorName']].to_string(index=False))
            print()
        
        # Try the specific indicator code for cardiovascular disease death rates
        # MDG_0000000007 is often used for age-standardized death rates
        # Let's try multiple potential codes
        potential_codes = [
            "WHS2_161",  # Age-standardized mortality rate by cause - Cardiovascular
            "SA_0000001444",  # Age-standardized death rates, ischaemic heart disease
            "MDG_0000000007",  # Age-standardized death rate
            "NCD_MORT_30_70",  # NCD mortality
            "MDG_0000000008",  # Another mortality indicator
        ]
        
        all_data = []
        
        for code in potential_codes:
            print(f"Trying indicator code: {code}")
            # Use OData filter to get only specified years at API level
            data = self.get_indicator_data(code, years=years)
            
            if data and 'value' in data:
                print(f"Found data for {code}")
                
                for item in data['value']:
                    try:
                        # For cardiovascular-specific indicators, include all data
                        # For general indicators, check if this is cardiovascular disease related
                        indicator_name = item.get('IndicatorName', '').lower()
                        if (code in ["WHS2_161", "SA_0000001444"] or 
                            any(term in indicator_name for term in ['cardiovascular', 'heart', 'circulatory', 'ischaemic'])):
                            record = {
                                'IndicatorCode': code,
                                'IndicatorName': item.get('IndicatorName', ''),
                                'Country': item.get('SpatialDim', ''),
                                'CountryCode': item.get('SpatialDimType', ''),
                                'Year': item.get('TimeDim', ''),
                                'Sex': self._parse_sex_dimension(item.get('Dim1', '')),
                                'DeathRate': item.get('NumericValue', None),
                                'DeathRate_Low': item.get('Low', None),
                                'DeathRate_High': item.get('High', None),
                                'Comments': item.get('Comments', ''),
                                'DataSource': item.get('DataSourceDim', ''),
                            }
                            
                            # If years were specified, API already filtered, but double-check
                            if years is None or int(record['Year']) in years:
                                all_data.append(record)
                                
                    except (ValueError, TypeError) as e:
                        print(f"Error processing record: {e}")
                        continue
        
        df = pd.DataFrame(all_data)
        
        # Clean and format the data
        if not df.empty:
            df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
            df['DeathRate'] = pd.to_numeric(df['DeathRate'], errors='coerce')
            df['DeathRate_Low'] = pd.to_numeric(df['DeathRate_Low'], errors='coerce')
            df['DeathRate_High'] = pd.to_numeric(df['DeathRate_High'], errors='coerce')
            
            # Sort by country, sex, and year
            df = df.sort_values(['Country', 'Sex', 'Year']).reset_index(drop=True)
        
        print(f"Retrieved {len(df)} cardiovascular death rate records")
        return df

    def search_indicators(self, search_term: str) -> pd.DataFrame:
        """
        Search for indicators containing a specific term.
        
        Args:
            search_term: Term to search for in indicator names
            
        Returns:
            DataFrame with matching indicators
        """
        try:
            url = f"{self.base_url}/Indicator"
            params = {"$filter": f"contains(IndicatorName,'{search_term}')"}
            response = self.session.get(url, params=params, timeout=30)
            response.raise_for_status()
            data = response.json()
            
            indicators = []
            for item in data.get('value', []):
                indicators.append({
                    'IndicatorCode': item.get('IndicatorCode', ''),
                    'IndicatorName': item.get('IndicatorName', ''),
                    'Language': item.get('Language', ''),
                    'PublishState': item.get('PublishState', '')
                })
            
            return pd.DataFrame(indicators)
        except requests.exceptions.RequestException as e:
            print(f"Error searching indicators: {e}")
            return pd.DataFrame()
    
    def list_all_indicators(self) -> pd.DataFrame:
        """
        Get a list of all available indicators from the WHO GHO API.
        
        Returns:
            DataFrame with all indicators (IndicatorCode, IndicatorName, etc.)
        """
        try:
            url = f"{self.base_url}/Indicator"
            response = self.session.get(url, timeout=30)
            response.raise_for_status()
            data = response.json()
            
            indicators = []
            for item in data.get('value', []):
                indicators.append({
                    'IndicatorCode': item.get('IndicatorCode', ''),
                    'IndicatorName': item.get('IndicatorName', ''),
                    'Language': item.get('Language', ''),
                    'PublishState': item.get('PublishState', '')
                })
            
            return pd.DataFrame(indicators)
        except requests.exceptions.RequestException as e:
            print(f"Error fetching indicators list: {e}")
            return pd.DataFrame()
    
    def get_indicator_years(self, indicator_code: str) -> List[int]:
        """
        Get list of available years for a specific indicator.
        
        Args:
            indicator_code: The WHO indicator code
            
        Returns:
            List of available years (sorted)
        """
        try:
            data = self.get_indicator_data(indicator_code)
            if not data or 'value' not in data:
                return []
            
            years = set()
            for item in data['value']:
                year = item.get('TimeDim')
                if year:
                    try:
                        years.add(int(year))
                    except (ValueError, TypeError):
                        continue
            
            return sorted(list(years))
        except Exception as e:
            print(f"Error getting years for {indicator_code}: {e}")
            return []
    
    def get_indicator_info(self, indicator_code: str) -> Dict:
        """
        Get information about an indicator including available years, countries, and sex categories.
        
        Args:
            indicator_code: The WHO indicator code
            
        Returns:
            Dictionary with indicator information
        """
        try:
            data = self.get_indicator_data(indicator_code)
            if not data or 'value' not in data:
                return {'indicator_code': indicator_code, 'error': 'No data found'}
            
            years = set()
            countries = set()
            sexes = set()
            
            for item in data['value']:
                year = item.get('TimeDim')
                if year:
                    try:
                        years.add(int(year))
                    except (ValueError, TypeError):
                        pass
                
                country = item.get('SpatialDim')
                if country:
                    countries.add(country)
                
                sex = item.get('Dim1', '')
                if sex:
                    sexes.add(sex)
            
            return {
                'indicator_code': indicator_code,
                'indicator_name': data['value'][0].get('IndicatorName', '') if data['value'] else '',
                'available_years': sorted(list(years)),
                'year_range': (min(years), max(years)) if years else None,
                'num_countries': len(countries),
                'sex_categories': list(sexes),
                'total_records': len(data['value'])
            }
        except Exception as e:
            return {'indicator_code': indicator_code, 'error': str(e)}

def main():
    """Main function to demonstrate usage of the WHO GHO API client."""
    
    # Set up command-line argument parsing
    parser = argparse.ArgumentParser(
        description="Download data from WHO Global Health Observatory (GHO) API"
    )
    parser.add_argument(
        "--data",
        choices=["hale", "cardio", "both", "all"],
        default="both",
        help="Which data to download: hale (HALE only), cardio (cardiovascular only), both (HALE and cardio), all (includes examples and analysis)"
    )
    parser.add_argument(
        "--years",
        type=str,
        default=None,
        help="Comma-separated list of years to filter (e.g., '2015,2020,2023') or range (e.g., '2015-2023'). If not specified, gets all available years."
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="data",
        help="Directory to save output files (default: data)"
    )
    parser.add_argument(
        "--hale-filename",
        type=str,
        default=None,
        help="Filename for HALE data CSV (default: who_hale_data.csv)"
    )
    parser.add_argument(
        "--cardio-filename",
        type=str,
        default=None,
        help="Filename for cardiovascular death rates CSV (default: who_cardiovascular_death_rates.csv)"
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Show detailed output including searches and analysis"
    )
    parser.add_argument(
        "--list-indicators",
        type=str,
        default=None,
        metavar="SEARCH_TERM",
        help="Search for indicators by term (e.g., 'cardiovascular', 'smoking'). If no term provided, lists all indicators."
    )
    parser.add_argument(
        "--indicator-info",
        type=str,
        default=None,
        metavar="INDICATOR_CODE",
        help="Get information about a specific indicator including available years (e.g., 'WHS2_161')"
    )
    
    args = parser.parse_args()
    
    # Handle indicator exploration commands
    client = WHOGHOClient()
    
    if args.list_indicators is not None:
        if args.list_indicators == "":
            # List all indicators
            print("=== Listing all available indicators ===")
            indicators_df = client.list_all_indicators()
            if not indicators_df.empty:
                print(f"Total indicators: {len(indicators_df)}")
                print("\nFirst 50 indicators:")
                print(indicators_df.head(50).to_string(index=False))
                if len(indicators_df) > 50:
                    print(f"\n... and {len(indicators_df) - 50} more. Use --list-indicators 'search_term' to filter.")
        else:
            # Search for indicators
            print(f"=== Searching for indicators containing '{args.list_indicators}' ===")
            indicators_df = client.search_indicators(args.list_indicators)
            if not indicators_df.empty:
                print(f"Found {len(indicators_df)} indicators:")
                print(indicators_df[['IndicatorCode', 'IndicatorName']].to_string(index=False))
            else:
                print("No indicators found.")
        return
    
    if args.indicator_info:
        print(f"=== Getting information for indicator: {args.indicator_info} ===")
        info = client.get_indicator_info(args.indicator_info)
        if 'error' in info:
            print(f"Error: {info['error']}")
        else:
            print(f"Indicator Code: {info['indicator_code']}")
            print(f"Indicator Name: {info['indicator_name']}")
            print(f"Available Years: {info['available_years']}")
            if info['year_range']:
                print(f"Year Range: {info['year_range'][0]} - {info['year_range'][1]}")
            print(f"Number of Countries: {info['num_countries']}")
            print(f"Sex Categories: {info['sex_categories']}")
            print(f"Total Records: {info['total_records']}")
        return
    
    # Parse years argument
    years = None
    if args.years:
        if '-' in args.years:
            # Range format: 2015-2023
            start, end = map(int, args.years.split('-'))
            years = list(range(start, end + 1))
        else:
            # Comma-separated list: 2015,2020,2023
            years = [int(y.strip()) for y in args.years.split(',')]
    
    # Create output directory if it doesn't exist
    os.makedirs(args.output_dir, exist_ok=True)
    
    # Determine which data to download
    download_hale = args.data in ["hale", "both", "all"]
    download_cardio = args.data in ["cardio", "both", "all"]
    show_examples = args.data == "all"
    
    hale_df = pd.DataFrame()
    cardio_df = pd.DataFrame()
    
    # Download HALE data if requested
    if download_hale:
        if args.verbose:
            print("=== Searching for HALE indicators ===")
            hale_indicators = client.search_indicators("healthy life expectancy")
            if not hale_indicators.empty:
                print("Found HALE indicators:")
                print(hale_indicators[['IndicatorCode', 'IndicatorName']].to_string(index=False))
                print()
        
        print("=== Downloading HALE data ===")
        hale_df = client.get_hale_data(years=years)
        
        if not hale_df.empty:
            print(f"Total records: {len(hale_df)}")
            print(f"Countries: {hale_df['Country'].nunique()}")
            print(f"Years covered: {hale_df['Year'].min():.0f} - {hale_df['Year'].max():.0f}")
            print(f"Sex categories: {hale_df['Sex'].unique()}")
            
            if args.verbose:
                print("\nSample data:")
                print(hale_df.head(10))
            
            # Save HALE data to CSV
            hale_filename = args.hale_filename or 'who_hale_data.csv'
            hale_path = os.path.join(args.output_dir, hale_filename)
            hale_df.to_csv(hale_path, index=False)
            print(f"\n=== HALE data saved to {hale_path} ===")
            
            if show_examples:
                # Example: Analyze data by sex
                print("\n=== HALE statistics by sex ===")
                sex_stats = hale_df.groupby('Sex')['HALE_Years'].agg(['count', 'mean', 'std']).round(2)
                print(sex_stats)
                
                # Example: Get countries with highest/lowest HALE (most recent data)
                print("\n=== Countries with highest/lowest HALE (most recent year) ===")
                latest_year = hale_df['Year'].max()
                latest_data = hale_df[(hale_df['Year'] == latest_year) & (hale_df['Sex'] == 'Both sexes')]
                
                if not latest_data.empty:
                    print(f"\nTop 10 countries with highest HALE in {latest_year:.0f}:")
                    top_10 = latest_data.nlargest(10, 'HALE_Years')[['Country', 'HALE_Years']]
                    print(top_10.to_string(index=False))
                    
                    print(f"\nBottom 10 countries with lowest HALE in {latest_year:.0f}:")
                    bottom_10 = latest_data.nsmallest(10, 'HALE_Years')[['Country', 'HALE_Years']]
                    print(bottom_10.to_string(index=False))
        else:
            print("No HALE data retrieved.")
    
    # Download cardiovascular data if requested
    if download_cardio:
        print("\n" + "="*60)
        print("=== CARDIOVASCULAR DISEASE DEATH RATES BY GENDER ===")
        print("="*60)
        
        # Get cardiovascular death rates
        cardio_df = client.get_cardiovascular_death_rates(years=years)
        
        if not cardio_df.empty:
            print(f"\nTotal cardiovascular death rate records: {len(cardio_df)}")
            print(f"Countries: {cardio_df['Country'].nunique()}")
            print(f"Years covered: {cardio_df['Year'].min():.0f} - {cardio_df['Year'].max():.0f}")
            print(f"Sex categories: {cardio_df['Sex'].unique()}")
            print(f"Indicators found: {cardio_df['IndicatorName'].unique()}")
            
            if args.verbose:
                print("\nSample cardiovascular death rate data:")
                print(cardio_df.head(10))
            
            # Save cardiovascular data to CSV
            cardio_filename = args.cardio_filename or 'who_cardiovascular_death_rates.csv'
            cardio_path = os.path.join(args.output_dir, cardio_filename)
            cardio_df.to_csv(cardio_path, index=False)
            print(f"\n=== Cardiovascular death rate data saved to {cardio_path} ===")
            
            if show_examples:
                # Analyze by gender
                print("\n=== Cardiovascular Death Rate Statistics by Gender ===")
                gender_stats = cardio_df.groupby('Sex')['DeathRate'].agg(['count', 'mean', 'std']).round(2)
                print(gender_stats)
                
                # Compare male vs female death rates
                latest_year = cardio_df['Year'].max()
                latest_cardio = cardio_df[cardio_df['Year'] == latest_year]
                
                if not latest_cardio.empty:
                    print(f"\n=== Gender Comparison for {latest_year:.0f} ===")
                    gender_comparison = latest_cardio.groupby('Sex')['DeathRate'].agg(['mean', 'std']).round(2)
                    print(gender_comparison)
                    
                    # Countries with highest/lowest death rates by gender
                    for sex in ['Male', 'Female']:
                        sex_data = latest_cardio[latest_cardio['Sex'] == sex]
                        if not sex_data.empty:
                            print(f"\nTop 10 countries with highest cardiovascular death rates ({sex}) in {latest_year:.0f}:")
                            top_10 = sex_data.nlargest(10, 'DeathRate')[['Country', 'DeathRate']]
                            print(top_10.to_string(index=False))
                            
                            print(f"\nBottom 10 countries with lowest cardiovascular death rates ({sex}) in {latest_year:.0f}:")
                            bottom_10 = sex_data.nsmallest(10, 'DeathRate')[['Country', 'DeathRate']]
                            print(bottom_10.to_string(index=False))
        else:
            print("No cardiovascular death rate data found.")
            if args.verbose:
                print("Trying alternative search terms...")
                alt_indicators = client.search_indicators("heart disease")
                if not alt_indicators.empty:
                    print("Found heart disease indicators:")
                    print(alt_indicators[['IndicatorCode', 'IndicatorName']].to_string(index=False))
    
    # Show examples if requested
    if show_examples:
        print("\n=== Getting countries list ===")
        countries_df = client.get_countries_list()
        if not countries_df.empty:
            print(f"Total countries/regions: {len(countries_df)}")
            print("Sample countries:")
            print(countries_df.head())

if __name__ == "__main__":
    main()